<a href="https://colab.research.google.com/github/EPRADDH/NLP_Natural_Language_Processing_Methods/blob/main/Different_types_of_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Frequency based Embedding

# 1. CountVectrization

https://colab.research.google.com/drive/1BqYjuYNROdJtb5maA0zlVKM57xwV080w?authuser=2


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
# set of documents
train = ['The sky is blue.','The sun is bright.']
test = ['The sun in the sky is bright', 'We can see the shining sun, the bright sun.']

# instantiate the vectorizer object
countvectorizer = CountVectorizer(analyzer= 'word', stop_words='english')

In [ ]:
# convert th documents into a matrix
count_wm = countvectorizer.fit_transform(train)
count_wm

<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [ ]:
# sparse matrix  count for Doc1 & Doc2
count_wm.toarray()   

array([[1, 0, 1, 0],
       [0, 1, 0, 1]])

In [ ]:
count_tokens = countvectorizer.get_feature_names()
count_tokens

['blue', 'bright', 'sky', 'sun']

In [ ]:
df_countvect = pd.DataFrame(data = count_wm.toarray(),index = ['Doc1','Doc2'],columns = count_tokens)

In [ ]:

df_countvect

blue  bright  sky  sun
Doc1     1       0    1    0
Doc2     0       1    0    1

#Exampal : 2

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
train = ('The sky is blue.','The sun is bright.')
test = ('The sun in the sky is bright', 'We can see the shining sun, the bright sun.')

In [ ]:
# instantiate the vectorizer object
# use analyzer is word and stop_words is english which are responsible for remove stop words and create word vocabulary
countvectorizer = CountVectorizer(analyzer='word' , stop_words='english')

countvectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
terms = countvectorizer.fit_transform(train)
term_vectors  = countvectorizer.transform(test)

In [ ]:
print("Sparse Matrix form of test data : \n")
print(term_vectors.todense())

print("Sparse Matrix form of test data : \n")
print(terms.todense())

Sparse Matrix form of test data : 

[[0 1 1 1]
 [0 1 0 2]]
Sparse Matrix form of test data : 

[[1 0 1 0]
 [0 1 0 1]]


# 2. TF-IDF vectorization

Example 1

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
# set of documents
train = ['The sky is blue.','The sun is bright.']
test = ['The sun in the sky is bright', 'We can see the shining sun, the bright sun.']

# instantiate the vectorizer object
tfidfvectorizer = TfidfVectorizer(analyzer='word',stop_words= 'english')

In [ ]:
# convert th documents into a matrix
tfidf_wm = tfidfvectorizer.fit_transform(train)

In [ ]:
# TF-IDF Score for Doc1 & Doc2
tfidf_wm.toarray() 

array([[0.70710678, 0.        , 0.70710678, 0.        ],
       [0.        , 0.70710678, 0.        , 0.70710678]])

In [ ]:
tfidf_tokens = tfidfvectorizer.get_feature_names()
tfidf_tokens

['blue', 'bright', 'sky', 'sun']

In [ ]:
df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),index = ['Doc1','Doc2'],columns = tfidf_tokens)

df_tfidfvect

blue    bright       sky       sun
Doc1  0.707107  0.000000  0.707107  0.000000
Doc2  0.000000  0.707107  0.000000  0.707107

Example 2

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
train = ('The sky is blue.','The sun is bright.')
test = ('The sun in the sky is bright', 'We can see the shining sun, the bright sun.')

In [ ]:
# instantiate the vectorizer object
# use analyzer is word and stop_words is english which are responsible for remove stop words and create word vocabulary
tfidfvectorizer = TfidfVectorizer(analyzer='word' , stop_words='english',)

In [ ]:
tfidfvectorizer.fit(train)
tfidf_train = tfidfvectorizer.transform(train)
tfidf_term_vectors  = tfidfvectorizer.transform(test)

In [ ]:
print("Sparse Matrix form of test data : \n")
print(tfidf_train.todense())

print("\nSparse Matrix form of test data : \n")
print(tfidf_term_vectors.todense())

Sparse Matrix form of test data : 

[[0.70710678 0.         0.70710678 0.        ]
 [0.         0.70710678 0.         0.70710678]]

Sparse Matrix form of test data : 

[[0.         0.57735027 0.57735027 0.57735027]
 [0.         0.4472136  0.         0.89442719]]


# TFIDF from scrach using coustom function

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
documentA = 'the man went out for a walk'
documentB = 'the children sat around the fire'

In [ ]:
bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

In [ ]:
# remove duplicate words.
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

In [ ]:
#create a dictionary of words and their occurence for each document in the corpus (collection of documents)

numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
    
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

In [ ]:
print(numOfWordsA)
print(numOfWordsB)

{'children': 0, 'the': 1, 'out': 1, 'went': 1, 'sat': 0, 'fire': 0, 'walk': 1, 'for': 1, 'around': 0, 'a': 1, 'man': 1}
{'children': 1, 'the': 2, 'out': 0, 'went': 0, 'sat': 1, 'fire': 1, 'walk': 0, 'for': 0, 'around': 1, 'a': 0, 'man': 0}


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

# Term Frequency (TF)

The number of times a word appears in a document divded by the total number of words in the document. Every document has its own term frequency.
Image for post

In [ ]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [ ]:
#compute the term frequency for each of our documents.
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

In [ ]:
print(tfA)
print(tfB)

{'children': 0.0, 'the': 0.14285714285714285, 'out': 0.14285714285714285, 'went': 0.14285714285714285, 'sat': 0.0, 'fire': 0.0, 'walk': 0.14285714285714285, 'for': 0.14285714285714285, 'around': 0.0, 'a': 0.14285714285714285, 'man': 0.14285714285714285}
{'children': 0.16666666666666666, 'the': 0.3333333333333333, 'out': 0.0, 'went': 0.0, 'sat': 0.16666666666666666, 'fire': 0.16666666666666666, 'walk': 0.0, 'for': 0.0, 'around': 0.16666666666666666, 'a': 0.0, 'man': 0.0}


# Inverse Data Frequency (IDF)
The log of the number of documents divided by the number of documents that contain the word w. Inverse data frequency determines the weight of rare words across all documents in the corpus.


In [ ]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [ ]:
idfs = computeIDF([numOfWordsA, numOfWordsB])

In [ ]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [ ]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])

In [ ]:
df

children  the       out      went  ...       for    around         a       man
0  0.000000  0.0  0.099021  0.099021  ...  0.099021  0.000000  0.099021  0.099021
1  0.115525  0.0  0.000000  0.000000  ...  0.000000  0.115525  0.000000  0.000000

[2 rows x 11 columns]

#### Rather than manually implementing TF-IDF ourselves, we could use the class provided by sklearn.

In [ ]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([documentA, documentB])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)

df

around  children      fire      for  ...       sat       the     walk     went
0  0.000000  0.000000  0.000000  0.42616  ...  0.000000  0.303216  0.42616  0.42616
1  0.407401  0.407401  0.407401  0.00000  ...  0.407401  0.579739  0.00000  0.00000

[2 rows x 10 columns]

#co-occurrence matrix

Before diving into the Co-Occurrence Matrix with a fixed context window, let’s discuss the disadvantages of the other two Frequency-based techniques.
Count Vector and TF-IDF do not capture the position in semantics, co-occurrences in the document, etc.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']
count_model = CountVectorizer(ngram_range=(1,1)) # default unigram model
X = count_model.fit_transform(docs)
# X[X > 0] = 1 # run this line if you don't want extra within-text cooccurence (see below)
Xc = (X.T * X) # this is co-occurrence matrix in sparse csr format
Xc.setdiag(0) # sometimes you want to fill same word cooccurence to 0
print(Xc.todense()) # print out matrix in dense format

[[0 0 0 0 3]
 [0 0 2 1 1]
 [0 2 0 1 1]
 [0 1 1 0 0]
 [3 1 1 0 0]]


Example:2

In [ ]:
def co_occurrence(sentences, window_size):
    from collections import defaultdict
    
    d = defaultdict(int)
    vocab = set()
    for text in sentences:
        # preprocessing (use tokenizer instead)
        text = text.lower().split()
        # iterate over sentences
        for i in range(len(text)):
            token = text[i]
            vocab.add(token)  # add to vocab
            next_token = text[i+1 : i+1+window_size]
            for t in next_token:
                key = tuple( sorted([t, token]) )
                d[key] += 1

      # formulate the dictionary into dataframe
    vocab = sorted(vocab) # sort vocab
    df = pd.DataFrame(data=np.zeros((len(vocab), len(vocab)), dtype=np.int16),
                      index=vocab,
                      columns=vocab)
    for key, value in d.items():
        df.at[key[0], key[1]] = value
        df.at[key[1], key[0]] = value
    return df        

In [ ]:
text = ["I go to school every day by bus .",
            "i go to theatre every night by bus"]

In [ ]:
df = co_occurrence(text, 2)

In [ ]:
df

.  bus  by  day  every  go  i  night  school  theatre  to
.        0    1   1    0      0   0  0      0       0        0   0
bus      1    0   2    1      0   0  0      1       0        0   0
by       1    2   0    1      2   0  0      1       0        0   0
day      0    1   1    0      1   0  0      0       1        0   0
every    0    0   2    1      0   0  0      1       1        1   2
go       0    0   0    0      0   0  2      0       1        1   2
i        0    0   0    0      0   2  0      0       0        0   2
night    0    1   1    0      1   0  0      0       0        1   0
school   0    0   0    1      1   1  0      0       0        0   1
theatre  0    0   0    0      1   1  0      1       0        0   1
to       0    0   0    0      2   2  2      0       1        1   0

In [ ]:
df = co_occurrence(text, 3)
df

.  bus  by  day  every  go  i  night  school  theatre  to
.        0    1   1    1      0   0  0      0       0        0   0
bus      1    0   2    1      2   0  0      1       0        0   0
by       1    2   0    1      2   0  0      1       1        1   0
day      1    1   1    0      1   0  0      0       1        0   1
every    0    2   2    1      0   2  0      1       1        1   2
go       0    0   0    0      2   0  2      0       1        1   2
i        0    0   0    0      0   2  0      0       1        1   2
night    0    1   1    0      1   0  0      0       0        1   1
school   0    0   1    1      1   1  1      0       0        0   1
theatre  0    0   1    0      1   1  1      1       0        0   1
to       0    0   0    1      2   2  2      1       1        1   0

# Embedding Layer

Example of Learning an Embedding

we will define the documents and their class labels.


In [ ]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
from keras.preprocessing.text import one_hot


In [ ]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)


[[24, 13], [40, 34], [35, 30], [8, 34], [24], [9], [46, 30], [15, 40], [46, 34], [29, 27, 13, 41]]


In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[24 13  0  0]
 [40 34  0  0]
 [35 30  0  0]
 [ 8 34  0  0]
 [24  0  0  0]
 [ 9  0  0  0]
 [46 30  0  0]
 [15 40  0  0]
 [46 34  0  0]
 [29 27 13 41]]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [ ]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 80.000001
